# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#24273a"

# Main text color
theme[main_fg]="#cad3f5"

# Title color for boxes
theme[title]="#c6a0f6"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#8bd5ca"

# Background color of selected item in processes box
theme[selected_bg]="#5b6078"

# Foreground color of selected item in processes box
theme[selected_fg]="#cad3f5"

# Color of inactive/disabled text
theme[inactive_fg]="#6e738d"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c6a0f6"

# Box outline and divider line color
theme[cpu_box]="#a6da95"
theme[mem_box]="#a6da95"
theme[net_box]="#a6da95"
theme[proc_box]="#a6da95"
theme[div_line]="#5b6078"

# Gradients for meters and graphs
theme[temp_start]="#8bd5ca"
theme[temp_mid]="#8aadf4"
theme[temp_end]="#a6da95"

theme[cpu_start]="#8bd5ca"
theme[cpu_mid]="#8aadf4"
theme[cpu_end]="#a6da95"

theme[free_start]="#8aadf4"
theme[free_mid]="#eed49f"
theme[free_end]="#eed49f"

theme[cached_start]="#eed49f"
theme[cached_mid]="#eed49f"
theme[cached_end]="#eed49f"

theme[available_start]="#8bd5ca"
theme[available_mid]="#8bd5ca"
theme[available_end]="#8bd5ca"

t
