# Background and foreground colors
background = #24273a
foreground = #cad3f5

# Standard colors
palette = 0=#24273a
palette = 1=#ed8796
palette = 2=#a6da95
palette = 3=#eed49f
palette = 4=#8aadf4
palette = 5=#c6a0f6
palette = 6=#8bd5ca
palette = 7=#b8c0e0

# Bright colors
palette = 8=#5b6078
palette = 9=#ee99a0
palette = 10=#a6da95
palette = 11=#f5a97f
palette = 12=#7dc4e4
palette = 13=#b7bdf8
palette = 14=#8bd5ca
palette = 15=#cad3f5
